[workspace.package]
version = "0.1.8"
edition = "2021"
authors = ["Yui Kitsu <kitsuyui+github@kitsuyui.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/kitsuyui/rust-playground"

[workspace.dependencies]
openssl-probe = "0.1.5"
reqwest = { version = "0.11.23", features = ["blocking"] }
ring = "0.17.7"
hex = "0.4.3"
tokio = "1.35.1"
pyo3 = { version = "0.20.0", features = ["extension-module"] }
pyo3-build-config = "0.20.0"

[workspace.dependencies.openssl]
version = "0.10.62"
features = ["vendored"]

[workspace]

resolver = "2"
members = [
    "c1",
    "c2",
    "python",
    "wasm",
]

default-members = [
    "c1",
    "c2",
]