[workspace.dependencies]
openssl-probe = "0.1.5"
reqwest = { version = "0.11.13", features = ["blocking"] }
ring = "0.16.20"
hex = "0.4.3"
tokio = "1.24.2"
[workspace.dependencies.openssl]
version = "0.10.45"
features = ["vendored"]

[workspace]

members = [
    "c1",
    "c2",
]
