[target.x86_64-unknown-linux-gnu]
pre-build = ["dpkg --add-architecture amd64 && apt install -y libssl-dev:amd64"]
[target.x86_64-unknown-linux-musl]
pre-build = ["dpkg --add-architecture amd64 && apt install -y libssl-dev:amd64"]
[target.aarch64-unknown-linux-gnu]
pre-build = ["dpkg --add-architecture arm64 && apt install -y libssl-dev:arm64"]
[target.aarch64-unknown-linux-musl]
pre-build = ["dpkg --add-architecture arm64 && apt install -y libssl-dev:arm64"]
[target.armv7-unknown-linux-gnueabihf]
pre-build = ["dpkg --add-architecture armhf && apt install -y libssl-dev:armhf"]
[target.armv7-unknown-linux-musleabihf]
pre-build = ["dpkg --add-architecture armhf && apt install -y libssl-dev:armhf"]
[target.arm-unknown-linux-gnueabihf]
pre-build = ["dpkg --add-architecture armhf && apt install -y libssl-dev:armhf"]
[target.arm-unknown-linux-musleabihf]
pre-build = ["dpkg --add-architecture armhf && apt install -y libssl-dev:armhf"]
[target.x86_64-pc-windows-gnu]
pre-build = ["dpkg --add-architecture arm64 && apt install -y libssl-dev:amd64"]
