name: Test build Python packages

on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    # "released" events are emitted either when directly be released or be edited from pre-released.
    types: [prereleased, released]

env:
  MACOS_POETRY_CACHE_PATH: "~/Library/Caches/pypoetry"

jobs:
  test_and_build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.8"
            os: "ubuntu-latest"
            poetry_cache_path: "~/.cache/pypoetry"
            poetry_tool_cache: "/opt/hostedtoolcache/Python"
          - python: "3.9"
            os: "ubuntu-latest"
            poetry_cache_path: "~/.cache/pypoetry"
            poetry_tool_cache: "/opt/hostedtoolcache/Python/"
          - python: "3.10"
            os: "ubuntu-latest"
            poetry_cache_path: "~/.cache/pypoetry"
            poetry_tool_cache: "/opt/hostedtoolcache/Python/"
          - python: "3.11"
            os: "ubuntu-latest"
            poetry_cache_path: "~/.cache/pypoetry"
            poetry_tool_cache: "/opt/hostedtoolcache/Python/"
          - python: "3.8"
            os: "macos-latest"
            poetry_cache_path: "~/Library/Caches/pypoetry"
            poetry_tool_cache: "/Users/runner/hostedtoolcache/Python"
          - python: "3.9"
            os: "macos-latest"
            poetry_cache_path: "~/Library/Caches/pypoetry"
            poetry_tool_cache: "/Users/runner/hostedtoolcache/Python"
          - python: "3.10"
            os: "macos-latest"
            poetry_cache_path: "~/Library/Caches/pypoetry"
            poetry_tool_cache: "/Users/runner/hostedtoolcache/Python"
          - python: "3.11"
            os: "macos-latest"
            poetry_cache_path: "~/Library/Caches/pypoetry"
            poetry_tool_cache: "/Users/runner/hostedtoolcache/Python"
          - python: "3.8"
            os: "windows-latest"
            poetry_cache_path: 'C:\Users\runneradmin\AppData\Local\pypoetry'
            poetry_tool_cache: 'C:\hostedtoolcache\windows\Python'
          - python: "3.9"
            os: "windows-latest"
            poetry_cache_path: 'C:\Users\runneradmin\AppData\Local\pypoetry'
            poetry_tool_cache: 'C:\hostedtoolcache\windows\Python'
          - python: "3.10"
            os: "windows-latest"
            poetry_cache_path: 'C:\Users\runneradmin\AppData\Local\pypoetry'
            poetry_tool_cache: 'C:\hostedtoolcache\windows\Python'
          - python: "3.11"
            os: "windows-latest"
            poetry_cache_path: 'C:\Users\runneradmin\AppData\Local\pypoetry'
            poetry_tool_cache: 'C:\hostedtoolcache\windows\Python'

        # TODO: arch is not supported yet (arm64, i386, x86_64, ...)
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - uses: actions/cache@v3
        name: poetry cache
        with:
          path: |
            ${{ matrix.poetry_tool_cache }}
            ${{ matrix.poetry_cache_path }}
          key: |
            ${{ runner.os }}-${{ matrix.python }}-poetry-${{ hashFiles('**/poetry.lock') }}
            ${{ runner.os }}-${{ matrix.python }}-poetry-

      - uses: abatilo/actions-poetry@v2
      - name: Install python dependencies
        run: poetry install

      - name: Check Python version
        if: matrix.os != 'windows-latest'
        run: |
          actual_version=$(poetry run python --version)
          expected_version="Python ${{ matrix.python }}"
          if [ "$actual_version" == *"$expected_version"* ]; then
            echo "Expected $expected_version, but got $actual_version"
            exit 1
          fi

      - name: packaging linux
        if: matrix.os == 'ubuntu-latest'
        run: poetry run maturin build --release --strip --interpreter python${{ matrix.python }}

      - name: packaging windows
        if: matrix.os == 'windows-latest'
        run: poetry run maturin build --release --strip --interpreter python${{ matrix.python }}

      - name: packaging darwin
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          poetry run maturin build --release --strip --interpreter python${{ matrix.python }} --target x86_64-apple-darwin
          poetry run maturin build --release --strip --interpreter python${{ matrix.python }} --target aarch64-apple-darwin

      - name: test
        if: matrix.os != 'windows-latest'
        run: |
          rm ../target/wheels/*
          python3 -m venv .venv
          source .venv/bin/activate
          pip install .
          pip install pytest
          pytest tests
          python -c 'from kitsuyui_rust_playground import my_calc; assert my_calc(1, 2, 3) == "9"; print("OK")'
          deactivate

      - uses: actions/upload-artifact@v3
        with:
          name: build_wheels
          path: target/wheels/

  publish:
    needs: test_and_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build_wheels
          path: target/wheels/

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'release' && github.event.release.prerelease
        with:
          packages-dir: target/wheels/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Publish distribution to PyPI
        if: github.event_name == 'release' && !github.event.release.prerelease
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: target/wheels/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
