name: tests
on: [push]
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      # For incremental builds
      CARGO_INCREMENTAL: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # For incremental builds
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: git-restore-mtime  # For incremental builds
        uses: chetan/git-restore-mtime-action@v1.2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: check formatting
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: check build
        run: cargo check

      - name: Coverage
        run: |
          cargo install cargo-llvm-cov || true  # when already cached
          cargo llvm-cov --lcov --output-path coverage.lcov

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
