name: wasm

on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    # "released" events are emitted either when directly be released or be edited from pre-released.
    types: [prereleased, released]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wasm
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - run: |
          cargo install wasm-pack
          # wasm-pack test --node --firefox --chrome --safari --headless
          wasm-pack build --release --target bundler --scope kitsuyui
          wasm-pack pack

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - if: github.event_name == 'release' && !github.event.release.prerelease
        run: wasm-pack publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
